Properly construct a callTip for pointers and symbols with breadcrumbs (T, [], *, etc)
Hackerpilot/dsymbol pull request #175
Opened 2021-12-04 00:51 UTC by RUSShyTwo

2021-12-05 09:57 UTC, WebFreak001 requested changes
this is missing tests

2021-12-05 10:13 UTC, WebFreak001 commented on src/dsymbol/conversion/second.d
> +		        }
mixed whitespaces with tabs here

2022-01-18 20:31 UTC, RUSShyTwo commented
literally nobody other than WebFreak001 care about this project

this is very sad and disappointing, what D people are doing? they busy programming in Java?

2022-01-18 20:45 UTC, WebFreak001 commented
can you add tests? this is a non-trivial change and tests always also help convey what the PR is meant to fulfill or not fulfill for other reviewers + helps the feature stay working across later changes.

2022-01-18 21:47 UTC, WebFreak001 commented on src/dsymbol/conversion/second.d
> +			while(index--)
wouldn't it be better to iterate over the breadcrumbs (maybe make a copy) instead of iterating over the characters for stability?

2022-10-13 17:44 UTC, WebFreak001 commented
moved to https://github.com/dlang-community/DCD/pull/680

2022-10-13 17:44 UTC, closed without merging